# .gitpod.yml
tasks:
  - name: aws-cli
    init: |
      cd /workspace
      curl -sSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip -q awscliv2.zip
      sudo ./aws/install
      cd "$THEIA_WORKSPACE_ROOT"
    env:
      AWS_CLI_AUTO_PROMPT: "on-partial"
